server:
  pack:
    port: 25566
    public_ip: "localhost:25566"
  app:
    port: 3000
    redirect_uri: "http://localhost:3000"
    client_id:
    client_secret: ""

alerts:
  set_night: 151
  set_day: 152
  give_meat: 250
  netherite_tools: 300
  netherite_armor: 350
  shuffle_inventory: 550
  totem_of_undying: 900
  dropper: 1000
  heal: 1300
  explosion: 5000D
  mega_sword: 0
  airdrop: 0
  dropper2: 0
  ad: 0
  ink: 0
  bad_trip: 0
  black_hole: 0
  casino: 0
  to_nether: 0
  kill_chefs: 0
  helpers: 0
  lucky_blocks: 0
  random_scale: 0

profanity:
  - негр
  - пидо
  - пида
  - niga
  - нигр
  - ниге
  - додик
  - петух
  - петуч
  - симп
  - simp
  - куколд
  - kukold
  - cuckold
  - fag
  - хуе
  - хуй
  - даун
  - кады
  - кадь
  - kadb
  - 4e4e
  - 4e4n
  - cheche
  - chechn
  - 4echn
  - che4n
  - 4eche
  - 4eche
  - негры пидоры
  - негры пидорасы
  - пидр
  - хохолы
  - хохол
  - дауны
  - пидорасы
  - пидоры
  - дауниха
  - Тыпидорас
  - faggot
  - гомик
  - педик
  - хач
  - жид
  - хиджаб
  - аутист
  - retard
  - virgin
  - incel
  - девственник
  - симп
  - инцел
  - cunt
  - гей
  - нацист
  - гитлер
  - фашизм
  - фашист
  - гомосек
  - русня
  - чурка
  - hurka
  - 4урка
  - 4urca
  - 4urka
  - churka
  - churca
  - chuрка
  - 4уrка
  - 4урka
  - 4уркф
  - чуркф
  - чyрка
  - чyрka
  - чyркa
  - холол
  - hohol
  - hochol
  - дауг
  - chock
  - greedy
  - hijab
  - down syndrome
  - autistic
  - петух
  - пeтух
  - петуx
  - cock
  - гтлер
  - пдр
  - пдорас
  - pdor
  - pdoras
  - romocek
  - пдоры
  - г0mосек
  - ретардер
  - пидек
  - пдек
  - куколд
  - cookold
  - cockold
  - 3.14door
  - IN_Цел
  - аутист
  - аутистик
  - aut_ist_ик
  - AUT_IST_ИК
  - autistик
  - хохлик
  - naZi
  - ngga
  - cooklusсlan
  - клукс
  - пдор